---
javascripts:
- base:
  - rails
  - jquery.tools.min
  - jquery-ui
  - jquery.notifyBar
  - jquery.hotkeys
  - showdown
  - utils
  - autocompleteBox
  - application
  - modules/new_question
  - modules/show_user
  - modules/show_question
  - MathJax/MathJax

- show:
  - wmd/jquery.wmd
  - wmd/jquery.wmd.mathjax
  - modules/single/question


stylesheets:
- base:
  - jquery-ui
  - compiled/application
  - autocomplete
- landing:
  - compiled/landing

